name: image_gallery
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:

  async_redux: ^22.0.0

  build_runner: ^2.4.8

  connectivity_plus: ^4.0.1

  cupertino_icons: ^1.0.6

  dartx: ^1.1.0

  flutter:
    sdk: flutter

  freezed: ^2.1.0+1

  freezed_annotation: ^2.1.0

  get_it: ^7.2.0

  go_router: ^8.0.5

  image_picker: ^1.0.2

  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
